runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: questionlog.app

# [END handlers]

# [START libraries]
libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

# [START env_variables]
env_variables:
  CLOUDSQL_CONNECTION_NAME: 'key-chalice-150719:us-central1:myinstance'
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: 'myinstance1'
# [END env_variables]
